
node {
   def commit_id
   def customImage
   stage('Preparation') {
     checkout scm
     sh "git rev-parse --short HEAD > .git/commit-id"                        
     commit_id = readFile('.git/commit-id').trim()
   }
   stage('test') {
     nodejs(nodeJSInstallationName: 'nodejs') {
       sh 'npm install --only=dev'
       sh 'npm test'
     }
   }
   stage('docker build') {
      customImage = docker.build("the2792/docker-nodejs-demo")
   }
   stage('docker push') {
     docker.withRegistry('https://registry.hub.docker.com', 'dockerhub') {
       customImage.push("${commit_id}")
       customImage.push("latest")
     }
   }
}