node {
   def commit_id
   stage('Preparation') {
     checkout scm
     sh "git rev-parse --short HEAD > .git/commit-id"                        
     commit_id = readFile('.git/commit-id').trim()
   }
   stage('test') {
     nodejs(nodeJSInstallationName: 'nodejs') {
       sh 'npm install --only=dev'
       sh 'npm test'
     }
   }
   stage('Building image') {
      steps{
          script {
            dockerImage = docker.build imagename
          }
        }
    }
   stage('Deploy Image') {
     docker.withRegistry('https://registry.hub.docker.com', 'dockerhub') {
      dockerImage.push("$commit_id")
      dockerImage.push('latest')
     }
   }
}